version: '3.8'

services:
  # Base de datos vectorial Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: buildbox-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - rag-network
    restart: unless-stopped

  # API RAG
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buildbox-rag-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      - qdrant
    networks:
      - rag-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # MinIO para almacenamiento de archivos (opcional)
  minio:
    image: minio/minio:latest
    container_name: buildbox-rag-minio
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY_ID:-minioadmin}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_ACCESS_KEY:-minioadmin123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
  minio_data:
    driver: local

networks:
  rag-network:
    driver: bridge 